context:
  version: "7.8.0"

package:
  name: schema-engine-cli
  version: ${{ version }}

source:
  url: https://github.com/prisma/prisma-engines/archive/${{ version }}.tar.gz
  sha256: 11d7bb84796fbf5038fe751d82e3a51abd9e518d78255768b7d19e433772b21d

build:
  number: 0
  skip: win or ppc64le

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
  host:
    - openssl

tests:
  - script:
      - schema-engine --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Engine components of Prisma ORM
  homepage: https://github.com/prisma/prisma-engines
  repository: https://github.com/prisma/prisma-engines

extra:
  recipe-maintainers:
    - danielnachun
