context:
  version: "6.16.0"

package:
  name: schema-engine-cli
  version: ${{ version }}

source:
  url: https://github.com/prisma/prisma-engines/archive/${{ version }}.tar.gz
  sha256: ccb2ee88527d9d9a5fc906293eac5e955690b18083910606ef26b9d3b05eb6f7

build:
  number: 0
  skip: win or ppc64le

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
  host:
    - openssl

tests:
  - script:
      - schema-engine --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Engine components of Prisma ORM
  homepage: https://github.com/prisma/prisma-engines
  repository: https://github.com/prisma/prisma-engines

extra:
  recipe-maintainers:
    - danielnachun
