context:
  version: "6.18.0"

package:
  name: schema-engine-cli
  version: ${{ version }}

source:
  url: https://github.com/prisma/prisma-engines/archive/${{ version }}.tar.gz
  sha256: 646ebd6d13aae5dcd59f94f6d54cf8ff99a62232dce794fb7042d16fb2c46787

build:
  number: 0
  skip: win or ppc64le

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
  host:
    - openssl

tests:
  - script:
      - schema-engine --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Engine components of Prisma ORM
  homepage: https://github.com/prisma/prisma-engines
  repository: https://github.com/prisma/prisma-engines

extra:
  recipe-maintainers:
    - danielnachun
