context:
  version: "7.7.0"

package:
  name: schema-engine-cli
  version: ${{ version }}

source:
  url: https://github.com/prisma/prisma-engines/archive/${{ version }}.tar.gz
  sha256: d47d459f059d62821475c0495fc2d62a7dc839761aa8178b15e6229ed7d2e35b

build:
  number: 0
  skip: win or ppc64le

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
  host:
    - openssl

tests:
  - script:
      - schema-engine --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Engine components of Prisma ORM
  homepage: https://github.com/prisma/prisma-engines
  repository: https://github.com/prisma/prisma-engines

extra:
  recipe-maintainers:
    - danielnachun
