context:
  version: "6.7.0"

package:
  name: schema-engine-cli
  version: ${{ version }}

source:
  url: https://github.com/prisma/prisma-engines/archive/${{ version }}.tar.gz
  sha256: a676a7ff9ac2c8fb362a7da0c0bc10949e23e1cc913849768a944675f6d1cc50

build:
  number: 0
  skip: win or ppc64le

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
  host:
    - openssl

tests:
  - script:
      - schema-engine --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Engine components of Prisma ORM
  homepage: https://github.com/prisma/prisma-engines
  repository: https://github.com/prisma/prisma-engines

extra:
  recipe-maintainers:
    - danielnachun
